apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest # Utilisation de l'image MariaDB officielle
          ports:
            - containerPort: 3306 # Port par défaut de MariaDB
          env:
            - name: MYSQL_ROOT_PASSWORD # Variable d'environnement pour définir le mot de passe root de MariaDB
              value: "votre_mot_de_passe_root"
