FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npx next -v

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/ /test

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]