name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build thibaut792/test/ -t ${{ secrets.DOCKER_USERNAME }}/test:${{ github.sha }}

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test:${{ github.sha }}

      - name: Checkout code for the update
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Deployment Image Tag
        run: |
          sed -i "s|${{ secrets.DOCKER_USERNAME }}/test:.*|${{ secrets.DOCKER_USERNAME }}/test:${{ github.sha }}|g" deployement/deploiement.yml
          git config --global user.email "thibautfiquet7@gmail.com"
          git config --global user.name "Thibaut792"
          git add .
          git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
