name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Déclencher la CI/CD uniquement sur les pushs sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Navigate to project directory
        run: |
          cd my-app
          ls -la

      - name: Install dependencies
        working-directory: my-app
        run: npm install

      - name: Build React App
        working-directory: my-app
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          GIT_SHA=$(git rev-parse HEAD | cut -c1-8)

          docker build -t thibaut792/test:$GIT_SHA -t thibaut792/test:latest -f my-app/Dockerfile .

          docker push thibaut792/test:$GIT_SHA
          docker push thibaut792/test:latest
